-- CreateEnum
CREATE TYPE "TableShape" AS ENUM ('RECTANGLE', 'SQUARE', 'CIRCLE');

-- AlterTable
ALTER TABLE "tables" ADD COLUMN     "floor" TEXT NOT NULL DEFAULT 'Main Floor',
ADD COLUMN     "height" DOUBLE PRECISION NOT NULL DEFAULT 90,
ADD COLUMN     "rotation" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "shape" "TableShape" NOT NULL DEFAULT 'RECTANGLE',
ADD COLUMN     "width" DOUBLE PRECISION NOT NULL DEFAULT 140;
